// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJTfsMam2r56g_bDqmQC7rqRdh1kFeU4',
    appId: '1:81452165653:android:cf13421ca29da075ed3c1c',
    messagingSenderId: '81452165653',
    projectId: 'steam-wishlist-manager',
    storageBucket: 'steam-wishlist-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzj4zp8RkLXEf1894HgWtXJJ42PnyHtM',
    appId: '1:81452165653:ios:cf5b206fd1cacdcbed3c1c',
    messagingSenderId: '81452165653',
    projectId: 'steam-wishlist-manager',
    storageBucket: 'steam-wishlist-manager.firebasestorage.app',
    iosBundleId: 'com.example.steamWishlistManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzj4zp8RkLXEf1894HgWtXJJ42PnyHtM',
    appId: '1:81452165653:ios:cf5b206fd1cacdcbed3c1c',
    messagingSenderId: '81452165653',
    projectId: 'steam-wishlist-manager',
    storageBucket: 'steam-wishlist-manager.firebasestorage.app',
    iosBundleId: 'com.example.steamWishlistManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1LX0HOJ5E6tPnruGNAhcK1nWwvMSKJWU',
    appId: '1:81452165653:web:0f54ac60419c9f95ed3c1c',
    messagingSenderId: '81452165653',
    projectId: 'steam-wishlist-manager',
    authDomain: 'steam-wishlist-manager.firebaseapp.com',
    storageBucket: 'steam-wishlist-manager.firebasestorage.app',
  );

}